name: Android E2E Testing
on:
  push:
    branches:
      - silasbw/android0

jobs:
  android:
    name: Android Testing
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
          check-latest: true
      - name: Install package dependencies
        run: yarn
      - name: Build mobile dependencies
        run: yarn build --scope @celo/mobile --include-filtered-dependencies
      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          script: cd packages/mobile && yarn run test:e2e:android -w 1
